// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsisbshqjyfesqbcymps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzaXNic2hxanlmZXNxYmN5bXBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMDA3OTIsImV4cCI6MjA3Mzc3Njc5Mn0.x7RgYAgROLD3hPi_5THthHvfXT2bwCkR6ZMXX3mdBO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});